# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesRole
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_role,
      attributes_class: Kubernetes::Types::RoleAttributes,
      outputs: { id: :id },
      map: [:metadata, :rule]
  end
  module Kubernetes
    include KubernetesRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
