# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_persistent_volume_claim_v1/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesPersistentVolumeClaimV1
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_persistent_volume_claim_v1,
      attributes_class: Kubernetes::Types::PersistentVolumeClaimV1Attributes,
      outputs: { id: :id },
      map: [:metadata, :spec],
      map_bool: [:wait_until_bound]
  end
  module Kubernetes
    include KubernetesPersistentVolumeClaimV1
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
