# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Kubernetes::Types
  include Dry.Types()

  class StorageClassAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Kubernetes::Types

    attribute :metadata, T::Array.of(T::Hash)
    attribute :storage_provisioner, T::String
    attribute? :allow_volume_expansion, T::Bool.optional
    attribute? :allowed_topologies, T::Array.of(T::Hash).optional
    attribute? :mount_options, T::Array.of(T::String).optional
    attribute? :parameters, T::Hash.optional
    attribute? :reclaim_policy, T::String.optional
    attribute? :volume_binding_mode, T::String.optional
  end
end
