# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_cluster_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesClusterRole
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_cluster_role,
      attributes_class: Kubernetes::Types::ClusterRoleAttributes,
      outputs: { id: :id },
      map: [:metadata],
      map_present: [:aggregation_rule, :rule]
  end
  module Kubernetes
    include KubernetesClusterRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
