# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Kubernetes::Types
  include Dry.Types()

  class ClusterRoleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Kubernetes::Types

    attribute :metadata, T::Array.of(T::Hash)
    attribute? :aggregation_rule, T::Array.of(T::Hash).optional
    attribute? :rule, T::Array.of(T::Hash).optional
  end
end
