# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_token_request_v1/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesTokenRequestV1
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_token_request_v1,
      attributes_class: Kubernetes::Types::TokenRequestV1Attributes,
      outputs: { id: :id },
      map: [:metadata],
      map_present: [:spec]
  end
  module Kubernetes
    include KubernetesTokenRequestV1
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
