# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_endpoints/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesEndpoints
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_endpoints,
      attributes_class: Kubernetes::Types::EndpointsAttributes,
      outputs: { id: :id },
      map: [:metadata],
      map_present: [:subset]
  end
  module Kubernetes
    include KubernetesEndpoints
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
