# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_env/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesEnv
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_env,
      attributes_class: Kubernetes::Types::EnvAttributes,
      outputs: { id: :id },
      map: [:api_version, :env, :kind, :metadata],
      map_present: [:container, :field_manager, :init_container],
      map_bool: [:force]
  end
  module Kubernetes
    include KubernetesEnv
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
