# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_node_taint/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesNodeTaint
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_node_taint,
      attributes_class: Kubernetes::Types::NodeTaintAttributes,
      outputs: { id: :id },
      map: [:metadata, :taint],
      map_present: [:field_manager],
      map_bool: [:force]
  end
  module Kubernetes
    include KubernetesNodeTaint
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
