# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Kubernetes::Types
  include Dry.Types()

  class NodeTaintAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Kubernetes::Types

    attribute :metadata, T::Array.of(T::Hash)
    attribute :taint, T::Array.of(T::Hash)
    attribute? :field_manager, T::String.optional
    attribute? :force, T::Bool.optional
  end
end
