# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Kubernetes::Types
  include Dry.Types()

  class RuntimeClassV1Attributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Kubernetes::Types

    attribute :handler, T::String
    attribute :metadata, T::Array.of(T::Hash)
  end
end
