# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_horizontal_pod_autoscaler_v2/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesHorizontalPodAutoscalerV2
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_horizontal_pod_autoscaler_v2,
      attributes_class: Kubernetes::Types::HorizontalPodAutoscalerV2Attributes,
      outputs: { id: :id },
      map: [:metadata, :spec]
  end
  module Kubernetes
    include KubernetesHorizontalPodAutoscalerV2
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
