# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_role_binding/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesRoleBinding
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_role_binding,
      attributes_class: Kubernetes::Types::RoleBindingAttributes,
      outputs: { id: :id },
      map: [:metadata, :role_ref, :subject]
  end
  module Kubernetes
    include KubernetesRoleBinding
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
