# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_manifest/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesManifest
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_manifest,
      attributes_class: Kubernetes::Types::ManifestAttributes,
      outputs: { id: :id },
      map: [:manifest],
      map_present: [:computed_fields, :field_manager, :wait, :wait_for]
  end
  module Kubernetes
    include KubernetesManifest
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
