# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Kubernetes::Types
  include Dry.Types()

  class ManifestAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Kubernetes::Types

    attribute :manifest, T::Any
    attribute? :computed_fields, T::Array.of(T::String).optional
    attribute? :field_manager, T::Array.of(T::Hash).optional
    attribute? :wait, T::Array.of(T::Hash).optional
    attribute? :wait_for, T::Hash.optional
  end
end
