# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_annotations/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesAnnotations
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_annotations,
      attributes_class: Kubernetes::Types::AnnotationsAttributes,
      outputs: { id: :id },
      map: [:api_version, :kind, :metadata],
      map_present: [:annotations, :field_manager, :template_annotations],
      map_bool: [:force]
  end
  module Kubernetes
    include KubernetesAnnotations
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
