# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_namespace/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesNamespace
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_namespace,
      attributes_class: Kubernetes::Types::NamespaceAttributes,
      outputs: { id: :id },
      map: [:metadata],
      map_bool: [:wait_for_default_service_account]
  end
  module Kubernetes
    include KubernetesNamespace
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
