# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_mutating_webhook_configuration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesMutatingWebhookConfiguration
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_mutating_webhook_configuration,
      attributes_class: Kubernetes::Types::MutatingWebhookConfigurationAttributes,
      outputs: { id: :id },
      map: [:metadata, :webhook]
  end
  module Kubernetes
    include KubernetesMutatingWebhookConfiguration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
