# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_config_map/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesConfigMap
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_config_map,
      attributes_class: Kubernetes::Types::ConfigMapAttributes,
      outputs: { id: :id },
      map: [:metadata],
      map_present: [:binary_data, :data],
      map_bool: [:immutable]
  end
  module Kubernetes
    include KubernetesConfigMap
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
