# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Kubernetes::Types
  include Dry.Types()

  class ConfigMapAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Kubernetes::Types

    attribute :metadata, T::Array.of(T::Hash)
    attribute? :binary_data, T::Hash.optional
    attribute? :data, T::Hash.optional
    attribute? :immutable, T::Bool.optional
  end
end
