# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_pod_disruption_budget_v1/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesPodDisruptionBudgetV1
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_pod_disruption_budget_v1,
      attributes_class: Kubernetes::Types::PodDisruptionBudgetV1Attributes,
      outputs: { id: :id },
      map: [:metadata, :spec]
  end
  module Kubernetes
    include KubernetesPodDisruptionBudgetV1
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
