# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_service/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesService
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_service,
      attributes_class: Kubernetes::Types::ServiceAttributes,
      outputs: { id: :id },
      map: [:metadata, :spec],
      map_bool: [:wait_for_load_balancer]
  end
  module Kubernetes
    include KubernetesService
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
