# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_secret_v1_data/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesSecretV1Data
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_secret_v1_data,
      attributes_class: Kubernetes::Types::SecretV1DataAttributes,
      outputs: { id: :id },
      map: [:data, :metadata],
      map_present: [:field_manager],
      map_bool: [:force]
  end
  module Kubernetes
    include KubernetesSecretV1Data
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
