# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_daemonset/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesDaemonset
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_daemonset,
      attributes_class: Kubernetes::Types::DaemonsetAttributes,
      outputs: { id: :id },
      map: [:metadata, :spec],
      map_bool: [:wait_for_rollout]
  end
  module Kubernetes
    include KubernetesDaemonset
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
