# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_job_v1/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesJobV1
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_job_v1,
      attributes_class: Kubernetes::Types::JobV1Attributes,
      outputs: { id: :id },
      map: [:metadata, :spec],
      map_bool: [:wait_for_completion]
  end
  module Kubernetes
    include KubernetesJobV1
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
