# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_priority_class_v1/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesPriorityClassV1
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_priority_class_v1,
      attributes_class: Kubernetes::Types::PriorityClassV1Attributes,
      outputs: { id: :id },
      map: [:metadata, :value],
      map_present: [:description, :preemption_policy],
      map_bool: [:global_default]
  end
  module Kubernetes
    include KubernetesPriorityClassV1
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
