# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Kubernetes::Types
  include Dry.Types()

  class PriorityClassV1Attributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Kubernetes::Types

    attribute :metadata, T::Array.of(T::Hash)
    attribute :value, T::Float
    attribute? :description, T::String.optional
    attribute? :global_default, T::Bool.optional
    attribute? :preemption_policy, T::String.optional
  end
end
