# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_network_policy_v1/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesNetworkPolicyV1
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_network_policy_v1,
      attributes_class: Kubernetes::Types::NetworkPolicyV1Attributes,
      outputs: { id: :id },
      map: [:metadata, :spec]
  end
  module Kubernetes
    include KubernetesNetworkPolicyV1
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
