# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Kubernetes::Types
  include Dry.Types()

  class DefaultServiceAccountV1Attributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Kubernetes::Types

    attribute :metadata, T::Array.of(T::Hash)
    attribute? :automount_service_account_token, T::Bool.optional
    attribute? :image_pull_secret, T::Array.of(T::Hash).optional
    attribute? :secret, T::Array.of(T::Hash).optional
  end
end
