# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_storage_class_v1/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesStorageClassV1
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_storage_class_v1,
      attributes_class: Kubernetes::Types::StorageClassV1Attributes,
      outputs: { id: :id },
      map: [:metadata, :storage_provisioner],
      map_present: [:allowed_topologies, :mount_options, :parameters, :reclaim_policy, :volume_binding_mode],
      map_bool: [:allow_volume_expansion]
  end
  module Kubernetes
    include KubernetesStorageClassV1
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
