# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_ingress_class/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesIngressClass
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_ingress_class,
      attributes_class: Kubernetes::Types::IngressClassAttributes,
      outputs: { id: :id },
      map: [:metadata, :spec]
  end
  module Kubernetes
    include KubernetesIngressClass
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
