# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_replication_controller/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesReplicationController
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_replication_controller,
      attributes_class: Kubernetes::Types::ReplicationControllerAttributes,
      outputs: { id: :id },
      map: [:metadata, :spec]
  end
  module Kubernetes
    include KubernetesReplicationController
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
