# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_role_v1/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesRoleV1
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_role_v1,
      attributes_class: Kubernetes::Types::RoleV1Attributes,
      outputs: { id: :id },
      map: [:metadata, :rule]
  end
  module Kubernetes
    include KubernetesRoleV1
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
