# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_persistent_volume/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesPersistentVolume
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_persistent_volume,
      attributes_class: Kubernetes::Types::PersistentVolumeAttributes,
      outputs: { id: :id },
      map: [:metadata, :spec]
  end
  module Kubernetes
    include KubernetesPersistentVolume
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
