# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_horizontal_pod_autoscaler/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesHorizontalPodAutoscaler
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_horizontal_pod_autoscaler,
      attributes_class: Kubernetes::Types::HorizontalPodAutoscalerAttributes,
      outputs: { id: :id },
      map: [:metadata, :spec]
  end
  module Kubernetes
    include KubernetesHorizontalPodAutoscaler
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
