# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_certificate_signing_request_v1/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesCertificateSigningRequestV1
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_certificate_signing_request_v1,
      attributes_class: Kubernetes::Types::CertificateSigningRequestV1Attributes,
      outputs: { id: :id },
      map: [:metadata, :spec],
      map_bool: [:auto_approve]
  end
  module Kubernetes
    include KubernetesCertificateSigningRequestV1
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
