# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_endpoint_slice_v1/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesEndpointSliceV1
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_endpoint_slice_v1,
      attributes_class: Kubernetes::Types::EndpointSliceV1Attributes,
      outputs: { id: :id },
      map: [:address_type, :endpoint, :metadata, :port]
  end
  module Kubernetes
    include KubernetesEndpointSliceV1
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
