# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_stateful_set/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesStatefulSet
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_stateful_set,
      attributes_class: Kubernetes::Types::StatefulSetAttributes,
      outputs: { id: :id },
      map: [:metadata, :spec],
      map_bool: [:wait_for_rollout]
  end
  module Kubernetes
    include KubernetesStatefulSet
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
