# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_secret/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesSecret
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_secret,
      attributes_class: Kubernetes::Types::SecretAttributes,
      outputs: { id: :id },
      map: [:metadata],
      map_present: [:binary_data, :binary_data_wo, :binary_data_wo_revision, :data_wo, :data_wo_revision, :type],
      map_bool: [:immutable, :wait_for_service_account_token]
  end
  module Kubernetes
    include KubernetesSecret
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
