# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Kubernetes::Types
  include Dry.Types()

  class SecretAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Kubernetes::Types

    attribute :metadata, T::Array.of(T::Hash)
    attribute? :binary_data, T::Hash.optional
    attribute? :binary_data_wo, T::Hash.optional
    attribute? :binary_data_wo_revision, T::Float.optional
    attribute? :data_wo, T::Hash.optional
    attribute? :data_wo_revision, T::Float.optional
    attribute? :immutable, T::Bool.optional
    attribute? :type, T::String.optional
    attribute? :wait_for_service_account_token, T::Bool.optional
  end
end
