# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_network_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesNetworkPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_network_policy,
      attributes_class: Kubernetes::Types::NetworkPolicyAttributes,
      outputs: { id: :id },
      map: [:metadata, :spec]
  end
  module Kubernetes
    include KubernetesNetworkPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
