# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_cron_job/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesCronJob
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_cron_job,
      attributes_class: Kubernetes::Types::CronJobAttributes,
      outputs: { id: :id },
      map: [:metadata, :spec]
  end
  module Kubernetes
    include KubernetesCronJob
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
