# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_labels/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesLabels
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_labels,
      attributes_class: Kubernetes::Types::LabelsAttributes,
      outputs: { id: :id },
      map: [:api_version, :kind, :labels, :metadata],
      map_present: [:field_manager],
      map_bool: [:force]
  end
  module Kubernetes
    include KubernetesLabels
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
