# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_service_v1/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesServiceV1
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_service_v1,
      attributes_class: Kubernetes::Types::ServiceV1Attributes,
      outputs: { id: :id },
      map: [:metadata, :spec],
      map_bool: [:wait_for_load_balancer]
  end
  module Kubernetes
    include KubernetesServiceV1
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
