# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_default_service_account/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesDefaultServiceAccount
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_default_service_account,
      attributes_class: Kubernetes::Types::DefaultServiceAccountAttributes,
      outputs: { id: :id },
      map: [:metadata],
      map_present: [:image_pull_secret, :secret],
      map_bool: [:automount_service_account_token]
  end
  module Kubernetes
    include KubernetesDefaultServiceAccount
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
