# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_pod/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesPod
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_pod,
      attributes_class: Kubernetes::Types::PodAttributes,
      outputs: { id: :id },
      map: [:metadata, :spec],
      map_present: [:target_state]
  end
  module Kubernetes
    include KubernetesPod
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
