# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_pod_security_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesPodSecurityPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_pod_security_policy,
      attributes_class: Kubernetes::Types::PodSecurityPolicyAttributes,
      outputs: { id: :id },
      map: [:metadata, :spec]
  end
  module Kubernetes
    include KubernetesPodSecurityPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
