# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/kubernetes_validating_webhook_configuration_v1/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module KubernetesValidatingWebhookConfigurationV1
    include Pangea::Resources::ResourceBuilder

    define_resource :kubernetes_validating_webhook_configuration_v1,
      attributes_class: Kubernetes::Types::ValidatingWebhookConfigurationV1Attributes,
      outputs: { id: :id },
      map: [:metadata, :webhook]
  end
  module Kubernetes
    include KubernetesValidatingWebhookConfigurationV1
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Kubernetes)
