# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a kubernetes_service_account_v1 resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::KubernetesServiceAccountV1 do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { metadata: [{ 'key1' => 'val1' }] } }

  describe ':kubernetes_service_account_v1' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_service_account_v1('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'kubernetes_service_account_v1', 'test')
        validate_required_attributes(config, [:metadata])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_service_account_v1('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:kubernetes_service_account_v1)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_service_account_v1('test', required_attrs)

        expect(ref.id).to eq("${kubernetes_service_account_v1.test.id}")
        expect(ref.default_secret_name).to eq("${kubernetes_service_account_v1.test.default_secret_name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_service_account_v1('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_service_account_v1', 'test')
        expect(config).not_to have_key('default_secret_name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ automount_service_account_token: true, image_pull_secret: [{ 'key1' => 'val1' }], secret: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_service_account_v1('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_service_account_v1', 'full')
        expect(config).to have_key('automount_service_account_token')
        expect(config).to have_key('image_pull_secret')
        expect(config).to have_key('secret')
      end
    end

    context 'optional attributes' do
      it 'includes automount_service_account_token when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_service_account_v1('opt', required_attrs.merge(automount_service_account_token: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_service_account_v1', 'opt')
        expect(config).to have_key('automount_service_account_token')
      end

      it 'omits automount_service_account_token when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_service_account_v1('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_service_account_v1', 'minimal')
        expect(config).not_to have_key('automount_service_account_token')
      end
      it 'includes image_pull_secret when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_service_account_v1('opt', required_attrs.merge(image_pull_secret: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_service_account_v1', 'opt')
        expect(config).to have_key('image_pull_secret')
      end

      it 'omits image_pull_secret when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_service_account_v1('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_service_account_v1', 'minimal')
        expect(config).not_to have_key('image_pull_secret')
      end
      it 'includes secret when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_service_account_v1('opt', required_attrs.merge(secret: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_service_account_v1', 'opt')
        expect(config).to have_key('secret')
      end

      it 'omits secret when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_service_account_v1('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_service_account_v1', 'minimal')
        expect(config).not_to have_key('secret')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts automount_service_account_token=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(automount_service_account_token: val)
          synth.kubernetes_service_account_v1("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'kubernetes_service_account_v1', "bool_#{val}")
          expect(config['automount_service_account_token']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_service_account_v1('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_service_account_v1', 'typed')
        expect(config['metadata']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_service_account_v1('first', required_attrs)
        synth.kubernetes_service_account_v1('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'kubernetes_service_account_v1')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :kubernetes_service_account_v1,
    method: :kubernetes_service_account_v1,
    required_attrs: { metadata: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id, :default_secret_name],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:automount_service_account_token]
end
