# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a kubernetes_namespace resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::KubernetesNamespace do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { metadata: [{ 'key1' => 'val1' }] } }

  describe ':kubernetes_namespace' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_namespace('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'kubernetes_namespace', 'test')
        validate_required_attributes(config, [:metadata])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_namespace('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:kubernetes_namespace)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_namespace('test', required_attrs)

        expect(ref.id).to eq("${kubernetes_namespace.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ wait_for_default_service_account: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_namespace('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_namespace', 'full')
        expect(config).to have_key('wait_for_default_service_account')
      end
    end

    context 'optional attributes' do
      it 'includes wait_for_default_service_account when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_namespace('opt', required_attrs.merge(wait_for_default_service_account: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_namespace', 'opt')
        expect(config).to have_key('wait_for_default_service_account')
      end

      it 'omits wait_for_default_service_account when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_namespace('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_namespace', 'minimal')
        expect(config).not_to have_key('wait_for_default_service_account')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts wait_for_default_service_account=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(wait_for_default_service_account: val)
          synth.kubernetes_namespace("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'kubernetes_namespace', "bool_#{val}")
          expect(config['wait_for_default_service_account']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_namespace('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_namespace', 'typed')
        expect(config['metadata']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_namespace('first', required_attrs)
        synth.kubernetes_namespace('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'kubernetes_namespace')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :kubernetes_namespace,
    method: :kubernetes_namespace,
    required_attrs: { metadata: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:wait_for_default_service_account]
end
