# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a kubernetes_certificate_signing_request resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::KubernetesCertificateSigningRequest do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { metadata: [{ 'key1' => 'val1' }], spec: [{ 'key1' => 'val1' }] } }

  describe ':kubernetes_certificate_signing_request' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_certificate_signing_request('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'kubernetes_certificate_signing_request', 'test')
        validate_required_attributes(config, [:metadata, :spec])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_certificate_signing_request('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:kubernetes_certificate_signing_request)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_certificate_signing_request('test', required_attrs)

        expect(ref.id).to eq("${kubernetes_certificate_signing_request.test.id}")
        expect(ref.certificate).to eq("${kubernetes_certificate_signing_request.test.certificate}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_certificate_signing_request('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_certificate_signing_request', 'test')
        expect(config).not_to have_key('certificate')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ auto_approve: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_certificate_signing_request('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_certificate_signing_request', 'full')
        expect(config).to have_key('auto_approve')
      end
    end

    context 'optional attributes' do
      it 'includes auto_approve when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_certificate_signing_request('opt', required_attrs.merge(auto_approve: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_certificate_signing_request', 'opt')
        expect(config).to have_key('auto_approve')
      end

      it 'omits auto_approve when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_certificate_signing_request('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_certificate_signing_request', 'minimal')
        expect(config).not_to have_key('auto_approve')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts auto_approve=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(auto_approve: val)
          synth.kubernetes_certificate_signing_request("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'kubernetes_certificate_signing_request', "bool_#{val}")
          expect(config['auto_approve']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_certificate_signing_request('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_certificate_signing_request', 'typed')
        expect(config['metadata']).to be_a(Array)
        expect(config['spec']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_certificate_signing_request('first', required_attrs)
        synth.kubernetes_certificate_signing_request('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'kubernetes_certificate_signing_request')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :kubernetes_certificate_signing_request,
    method: :kubernetes_certificate_signing_request,
    required_attrs: { metadata: [{ 'key1' => 'val1' }], spec: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id, :certificate],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:auto_approve]
end
