# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a kubernetes_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::KubernetesRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { metadata: [{ 'key1' => 'val1' }], rule: [{ 'key1' => 'val1' }] } }

  describe ':kubernetes_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'kubernetes_role', 'test')
        validate_required_attributes(config, [:metadata, :rule])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:kubernetes_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_role('test', required_attrs)

        expect(ref.id).to eq("${kubernetes_role.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_role', 'typed')
        expect(config['metadata']).to be_a(Array)
        expect(config['rule']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_role('first', required_attrs)
        synth.kubernetes_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'kubernetes_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :kubernetes_role,
    method: :kubernetes_role,
    required_attrs: { metadata: [{ 'key1' => 'val1' }], rule: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
