# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a kubernetes_persistent_volume_claim resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::KubernetesPersistentVolumeClaim do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { metadata: [{ 'key1' => 'val1' }], spec: [{ 'key1' => 'val1' }] } }

  describe ':kubernetes_persistent_volume_claim' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_persistent_volume_claim('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'kubernetes_persistent_volume_claim', 'test')
        validate_required_attributes(config, [:metadata, :spec])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_persistent_volume_claim('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:kubernetes_persistent_volume_claim)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_persistent_volume_claim('test', required_attrs)

        expect(ref.id).to eq("${kubernetes_persistent_volume_claim.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ wait_until_bound: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_persistent_volume_claim('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_persistent_volume_claim', 'full')
        expect(config).to have_key('wait_until_bound')
      end
    end

    context 'optional attributes' do
      it 'includes wait_until_bound when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_persistent_volume_claim('opt', required_attrs.merge(wait_until_bound: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_persistent_volume_claim', 'opt')
        expect(config).to have_key('wait_until_bound')
      end

      it 'omits wait_until_bound when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_persistent_volume_claim('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_persistent_volume_claim', 'minimal')
        expect(config).not_to have_key('wait_until_bound')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts wait_until_bound=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(wait_until_bound: val)
          synth.kubernetes_persistent_volume_claim("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'kubernetes_persistent_volume_claim', "bool_#{val}")
          expect(config['wait_until_bound']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_persistent_volume_claim('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_persistent_volume_claim', 'typed')
        expect(config['metadata']).to be_a(Array)
        expect(config['spec']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_persistent_volume_claim('first', required_attrs)
        synth.kubernetes_persistent_volume_claim('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'kubernetes_persistent_volume_claim')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :kubernetes_persistent_volume_claim,
    method: :kubernetes_persistent_volume_claim,
    required_attrs: { metadata: [{ 'key1' => 'val1' }], spec: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:wait_until_bound]
end
