# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a kubernetes_ingress resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::KubernetesIngress do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { metadata: [{ 'key1' => 'val1' }], spec: [{ 'key1' => 'val1' }] } }

  describe ':kubernetes_ingress' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_ingress('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'kubernetes_ingress', 'test')
        validate_required_attributes(config, [:metadata, :spec])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_ingress('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:kubernetes_ingress)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_ingress('test', required_attrs)

        expect(ref.id).to eq("${kubernetes_ingress.test.id}")
        expect(ref.status).to eq("${kubernetes_ingress.test.status}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_ingress('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_ingress', 'test')
        expect(config).not_to have_key('status')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ wait_for_load_balancer: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_ingress('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_ingress', 'full')
        expect(config).to have_key('wait_for_load_balancer')
      end
    end

    context 'optional attributes' do
      it 'includes wait_for_load_balancer when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_ingress('opt', required_attrs.merge(wait_for_load_balancer: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_ingress', 'opt')
        expect(config).to have_key('wait_for_load_balancer')
      end

      it 'omits wait_for_load_balancer when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_ingress('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_ingress', 'minimal')
        expect(config).not_to have_key('wait_for_load_balancer')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts wait_for_load_balancer=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(wait_for_load_balancer: val)
          synth.kubernetes_ingress("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'kubernetes_ingress', "bool_#{val}")
          expect(config['wait_for_load_balancer']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_ingress('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_ingress', 'typed')
        expect(config['metadata']).to be_a(Array)
        expect(config['spec']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_ingress('first', required_attrs)
        synth.kubernetes_ingress('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'kubernetes_ingress')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :kubernetes_ingress,
    method: :kubernetes_ingress,
    required_attrs: { metadata: [{ 'key1' => 'val1' }], spec: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id, :status],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:wait_for_load_balancer]
end
