# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a kubernetes_storage_class resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::KubernetesStorageClass do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { metadata: [{ 'key1' => 'val1' }], storage_provisioner: 'test-value' } }

  describe ':kubernetes_storage_class' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'kubernetes_storage_class', 'test')
        validate_required_attributes(config, [:metadata, :storage_provisioner])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_storage_class('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:kubernetes_storage_class)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_storage_class('test', required_attrs)

        expect(ref.id).to eq("${kubernetes_storage_class.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allow_volume_expansion: true, allowed_topologies: [{ 'key1' => 'val1' }], mount_options: ['test-value'], parameters: { 'key1' => 'val1' }, reclaim_policy: 'test-value', volume_binding_mode: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_storage_class', 'full')
        expect(config).to have_key('allow_volume_expansion')
        expect(config).to have_key('allowed_topologies')
        expect(config).to have_key('mount_options')
        expect(config).to have_key('parameters')
        expect(config).to have_key('reclaim_policy')
        expect(config).to have_key('volume_binding_mode')
      end
    end

    context 'optional attributes' do
      it 'includes allow_volume_expansion when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('opt', required_attrs.merge(allow_volume_expansion: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_storage_class', 'opt')
        expect(config).to have_key('allow_volume_expansion')
      end

      it 'omits allow_volume_expansion when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_storage_class', 'minimal')
        expect(config).not_to have_key('allow_volume_expansion')
      end
      it 'includes allowed_topologies when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('opt', required_attrs.merge(allowed_topologies: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_storage_class', 'opt')
        expect(config).to have_key('allowed_topologies')
      end

      it 'omits allowed_topologies when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_storage_class', 'minimal')
        expect(config).not_to have_key('allowed_topologies')
      end
      it 'includes mount_options when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('opt', required_attrs.merge(mount_options: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_storage_class', 'opt')
        expect(config).to have_key('mount_options')
      end

      it 'omits mount_options when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_storage_class', 'minimal')
        expect(config).not_to have_key('mount_options')
      end
      it 'includes parameters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('opt', required_attrs.merge(parameters: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_storage_class', 'opt')
        expect(config).to have_key('parameters')
      end

      it 'omits parameters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_storage_class', 'minimal')
        expect(config).not_to have_key('parameters')
      end
      it 'includes reclaim_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('opt', required_attrs.merge(reclaim_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_storage_class', 'opt')
        expect(config).to have_key('reclaim_policy')
      end

      it 'omits reclaim_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_storage_class', 'minimal')
        expect(config).not_to have_key('reclaim_policy')
      end
      it 'includes volume_binding_mode when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('opt', required_attrs.merge(volume_binding_mode: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_storage_class', 'opt')
        expect(config).to have_key('volume_binding_mode')
      end

      it 'omits volume_binding_mode when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_storage_class', 'minimal')
        expect(config).not_to have_key('volume_binding_mode')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts allow_volume_expansion=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_volume_expansion: val)
          synth.kubernetes_storage_class("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'kubernetes_storage_class', "bool_#{val}")
          expect(config['allow_volume_expansion']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_storage_class', 'typed')
        expect(config['metadata']).to be_a(Array)
        expect(config['storage_provisioner']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_storage_class('first', required_attrs)
        synth.kubernetes_storage_class('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'kubernetes_storage_class')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :kubernetes_storage_class,
    method: :kubernetes_storage_class,
    required_attrs: { metadata: [{ 'key1' => 'val1' }], storage_provisioner: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:allow_volume_expansion]
end
