# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a kubernetes_ingress_class_v1 resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::KubernetesIngressClassV1 do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { metadata: [{ 'key1' => 'val1' }], spec: [{ 'key1' => 'val1' }] } }

  describe ':kubernetes_ingress_class_v1' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_ingress_class_v1('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'kubernetes_ingress_class_v1', 'test')
        validate_required_attributes(config, [:metadata, :spec])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_ingress_class_v1('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:kubernetes_ingress_class_v1)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_ingress_class_v1('test', required_attrs)

        expect(ref.id).to eq("${kubernetes_ingress_class_v1.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_ingress_class_v1('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_ingress_class_v1', 'typed')
        expect(config['metadata']).to be_a(Array)
        expect(config['spec']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_ingress_class_v1('first', required_attrs)
        synth.kubernetes_ingress_class_v1('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'kubernetes_ingress_class_v1')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :kubernetes_ingress_class_v1,
    method: :kubernetes_ingress_class_v1,
    required_attrs: { metadata: [{ 'key1' => 'val1' }], spec: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
