# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a kubernetes_secret_v1 resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::KubernetesSecretV1 do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { metadata: [{ 'key1' => 'val1' }] } }

  describe ':kubernetes_secret_v1' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'test')
        validate_required_attributes(config, [:metadata])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_secret_v1('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:kubernetes_secret_v1)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_secret_v1('test', required_attrs)

        expect(ref.id).to eq("${kubernetes_secret_v1.test.id}")
        expect(ref.data).to eq("${kubernetes_secret_v1.test.data}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'test')
        expect(config).not_to have_key('data')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ binary_data: { 'key1' => 'val1' }, binary_data_wo: { 'key1' => 'val1' }, binary_data_wo_revision: 3.14, data_wo: { 'key1' => 'val1' }, data_wo_revision: 3.14, immutable: true, type: 'test-value', wait_for_service_account_token: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'full')
        expect(config).to have_key('binary_data')
        expect(config).to have_key('binary_data_wo')
        expect(config).to have_key('binary_data_wo_revision')
        expect(config).to have_key('data_wo')
        expect(config).to have_key('data_wo_revision')
        expect(config).to have_key('immutable')
        expect(config).to have_key('type')
        expect(config).to have_key('wait_for_service_account_token')
      end
    end

    context 'optional attributes' do
      it 'includes binary_data when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('opt', required_attrs.merge(binary_data: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'opt')
        expect(config).to have_key('binary_data')
      end

      it 'omits binary_data when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'minimal')
        expect(config).not_to have_key('binary_data')
      end
      it 'includes binary_data_wo when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('opt', required_attrs.merge(binary_data_wo: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'opt')
        expect(config).to have_key('binary_data_wo')
      end

      it 'omits binary_data_wo when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'minimal')
        expect(config).not_to have_key('binary_data_wo')
      end
      it 'includes binary_data_wo_revision when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('opt', required_attrs.merge(binary_data_wo_revision: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'opt')
        expect(config).to have_key('binary_data_wo_revision')
      end

      it 'omits binary_data_wo_revision when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'minimal')
        expect(config).not_to have_key('binary_data_wo_revision')
      end
      it 'includes data_wo when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('opt', required_attrs.merge(data_wo: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'opt')
        expect(config).to have_key('data_wo')
      end

      it 'omits data_wo when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'minimal')
        expect(config).not_to have_key('data_wo')
      end
      it 'includes data_wo_revision when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('opt', required_attrs.merge(data_wo_revision: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'opt')
        expect(config).to have_key('data_wo_revision')
      end

      it 'omits data_wo_revision when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'minimal')
        expect(config).not_to have_key('data_wo_revision')
      end
      it 'includes immutable when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('opt', required_attrs.merge(immutable: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'opt')
        expect(config).to have_key('immutable')
      end

      it 'omits immutable when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'minimal')
        expect(config).not_to have_key('immutable')
      end
      it 'includes type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('opt', required_attrs.merge(type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'opt')
        expect(config).to have_key('type')
      end

      it 'omits type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'minimal')
        expect(config).not_to have_key('type')
      end
      it 'includes wait_for_service_account_token when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('opt', required_attrs.merge(wait_for_service_account_token: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'opt')
        expect(config).to have_key('wait_for_service_account_token')
      end

      it 'omits wait_for_service_account_token when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'minimal')
        expect(config).not_to have_key('wait_for_service_account_token')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:binary_data, :data]
        expect(sensitive_fields).to include(:binary_data)
        expect(sensitive_fields).to include(:data)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts immutable=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(immutable: val)
          synth.kubernetes_secret_v1("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'kubernetes_secret_v1', "bool_#{val}")
          expect(config['immutable']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts wait_for_service_account_token=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(wait_for_service_account_token: val)
          synth.kubernetes_secret_v1("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'kubernetes_secret_v1', "bool_#{val}")
          expect(config['wait_for_service_account_token']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_secret_v1', 'typed')
        expect(config['metadata']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_secret_v1('first', required_attrs)
        synth.kubernetes_secret_v1('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'kubernetes_secret_v1')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :kubernetes_secret_v1,
    method: :kubernetes_secret_v1,
    required_attrs: { metadata: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id, :data],
    sensitive_fields: [:binary_data, :data],
    immutable_fields: [],
    boolean_fields: [:immutable, :wait_for_service_account_token]
end
