# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a kubernetes_config_map resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::KubernetesConfigMap do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { metadata: [{ 'key1' => 'val1' }] } }

  describe ':kubernetes_config_map' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_config_map('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'kubernetes_config_map', 'test')
        validate_required_attributes(config, [:metadata])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_config_map('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:kubernetes_config_map)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_config_map('test', required_attrs)

        expect(ref.id).to eq("${kubernetes_config_map.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ binary_data: { 'key1' => 'val1' }, data: { 'key1' => 'val1' }, immutable: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_config_map('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_config_map', 'full')
        expect(config).to have_key('binary_data')
        expect(config).to have_key('data')
        expect(config).to have_key('immutable')
      end
    end

    context 'optional attributes' do
      it 'includes binary_data when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_config_map('opt', required_attrs.merge(binary_data: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_config_map', 'opt')
        expect(config).to have_key('binary_data')
      end

      it 'omits binary_data when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_config_map('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_config_map', 'minimal')
        expect(config).not_to have_key('binary_data')
      end
      it 'includes data when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_config_map('opt', required_attrs.merge(data: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_config_map', 'opt')
        expect(config).to have_key('data')
      end

      it 'omits data when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_config_map('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_config_map', 'minimal')
        expect(config).not_to have_key('data')
      end
      it 'includes immutable when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_config_map('opt', required_attrs.merge(immutable: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_config_map', 'opt')
        expect(config).to have_key('immutable')
      end

      it 'omits immutable when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_config_map('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_config_map', 'minimal')
        expect(config).not_to have_key('immutable')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts immutable=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(immutable: val)
          synth.kubernetes_config_map("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'kubernetes_config_map', "bool_#{val}")
          expect(config['immutable']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_config_map('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_config_map', 'typed')
        expect(config['metadata']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_config_map('first', required_attrs)
        synth.kubernetes_config_map('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'kubernetes_config_map')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :kubernetes_config_map,
    method: :kubernetes_config_map,
    required_attrs: { metadata: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:immutable]
end
