# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a kubernetes_priority_class_v1 resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::KubernetesPriorityClassV1 do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { metadata: [{ 'key1' => 'val1' }], value: 3.14 } }

  describe ':kubernetes_priority_class_v1' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_priority_class_v1('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'kubernetes_priority_class_v1', 'test')
        validate_required_attributes(config, [:metadata, :value])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_priority_class_v1('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:kubernetes_priority_class_v1)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_priority_class_v1('test', required_attrs)

        expect(ref.id).to eq("${kubernetes_priority_class_v1.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', global_default: true, preemption_policy: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_priority_class_v1('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_priority_class_v1', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('global_default')
        expect(config).to have_key('preemption_policy')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_priority_class_v1('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_priority_class_v1', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_priority_class_v1('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_priority_class_v1', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes global_default when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_priority_class_v1('opt', required_attrs.merge(global_default: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_priority_class_v1', 'opt')
        expect(config).to have_key('global_default')
      end

      it 'omits global_default when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_priority_class_v1('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_priority_class_v1', 'minimal')
        expect(config).not_to have_key('global_default')
      end
      it 'includes preemption_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_priority_class_v1('opt', required_attrs.merge(preemption_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_priority_class_v1', 'opt')
        expect(config).to have_key('preemption_policy')
      end

      it 'omits preemption_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_priority_class_v1('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_priority_class_v1', 'minimal')
        expect(config).not_to have_key('preemption_policy')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts global_default=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(global_default: val)
          synth.kubernetes_priority_class_v1("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'kubernetes_priority_class_v1', "bool_#{val}")
          expect(config['global_default']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_priority_class_v1('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_priority_class_v1', 'typed')
        expect(config['metadata']).to be_a(Array)
        expect(config['value']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_priority_class_v1('first', required_attrs)
        synth.kubernetes_priority_class_v1('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'kubernetes_priority_class_v1')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :kubernetes_priority_class_v1,
    method: :kubernetes_priority_class_v1,
    required_attrs: { metadata: [{ 'key1' => 'val1' }], value: 3.14 },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:global_default]
end
