# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a kubernetes_annotations resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::KubernetesAnnotations do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { api_version: 'test-value', kind: 'test-value', metadata: [{ 'key1' => 'val1' }] } }

  describe ':kubernetes_annotations' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_annotations('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'kubernetes_annotations', 'test')
        validate_required_attributes(config, [:api_version, :kind, :metadata])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_annotations('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:kubernetes_annotations)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_annotations('test', required_attrs)

        expect(ref.id).to eq("${kubernetes_annotations.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ annotations: { 'key1' => 'val1' }, field_manager: 'test-value', force: true, template_annotations: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_annotations('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_annotations', 'full')
        expect(config).to have_key('annotations')
        expect(config).to have_key('field_manager')
        expect(config).to have_key('force')
        expect(config).to have_key('template_annotations')
      end
    end

    context 'optional attributes' do
      it 'includes annotations when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_annotations('opt', required_attrs.merge(annotations: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_annotations', 'opt')
        expect(config).to have_key('annotations')
      end

      it 'omits annotations when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_annotations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_annotations', 'minimal')
        expect(config).not_to have_key('annotations')
      end
      it 'includes field_manager when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_annotations('opt', required_attrs.merge(field_manager: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_annotations', 'opt')
        expect(config).to have_key('field_manager')
      end

      it 'omits field_manager when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_annotations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_annotations', 'minimal')
        expect(config).not_to have_key('field_manager')
      end
      it 'includes force when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_annotations('opt', required_attrs.merge(force: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_annotations', 'opt')
        expect(config).to have_key('force')
      end

      it 'omits force when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_annotations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_annotations', 'minimal')
        expect(config).not_to have_key('force')
      end
      it 'includes template_annotations when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_annotations('opt', required_attrs.merge(template_annotations: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_annotations', 'opt')
        expect(config).to have_key('template_annotations')
      end

      it 'omits template_annotations when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_annotations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_annotations', 'minimal')
        expect(config).not_to have_key('template_annotations')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts force=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(force: val)
          synth.kubernetes_annotations("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'kubernetes_annotations', "bool_#{val}")
          expect(config['force']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_annotations('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_annotations', 'typed')
        expect(config['api_version']).to be_a(String)
        expect(config['kind']).to be_a(String)
        expect(config['metadata']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_annotations('first', required_attrs)
        synth.kubernetes_annotations('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'kubernetes_annotations')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :kubernetes_annotations,
    method: :kubernetes_annotations,
    required_attrs: { api_version: 'test-value', kind: 'test-value', metadata: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:force]
end
