# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a kubernetes_manifest resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::KubernetesManifest do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { manifest: 'test-value' } }

  describe ':kubernetes_manifest' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_manifest('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'kubernetes_manifest', 'test')
        validate_required_attributes(config, [:manifest])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_manifest('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:kubernetes_manifest)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.kubernetes_manifest('test', required_attrs)

        expect(ref.id).to eq("${kubernetes_manifest.test.id}")
        expect(ref.object).to eq("${kubernetes_manifest.test.object}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_manifest('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_manifest', 'test')
        expect(config).not_to have_key('object')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ computed_fields: ['test-value'], field_manager: [{ 'key1' => 'val1' }], wait: [{ 'key1' => 'val1' }], wait_for: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_manifest('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_manifest', 'full')
        expect(config).to have_key('computed_fields')
        expect(config).to have_key('field_manager')
        expect(config).to have_key('wait')
        expect(config).to have_key('wait_for')
      end
    end

    context 'optional attributes' do
      it 'includes computed_fields when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_manifest('opt', required_attrs.merge(computed_fields: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_manifest', 'opt')
        expect(config).to have_key('computed_fields')
      end

      it 'omits computed_fields when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_manifest('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_manifest', 'minimal')
        expect(config).not_to have_key('computed_fields')
      end
      it 'includes field_manager when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_manifest('opt', required_attrs.merge(field_manager: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_manifest', 'opt')
        expect(config).to have_key('field_manager')
      end

      it 'omits field_manager when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_manifest('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_manifest', 'minimal')
        expect(config).not_to have_key('field_manager')
      end
      it 'includes wait when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_manifest('opt', required_attrs.merge(wait: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_manifest', 'opt')
        expect(config).to have_key('wait')
      end

      it 'omits wait when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_manifest('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_manifest', 'minimal')
        expect(config).not_to have_key('wait')
      end
      it 'includes wait_for when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_manifest('opt', required_attrs.merge(wait_for: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_manifest', 'opt')
        expect(config).to have_key('wait_for')
      end

      it 'omits wait_for when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_manifest('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'kubernetes_manifest', 'minimal')
        expect(config).not_to have_key('wait_for')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_manifest('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'kubernetes_manifest', 'typed')
        expect(config['manifest']).to be_a(Object)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.kubernetes_manifest('first', required_attrs)
        synth.kubernetes_manifest('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'kubernetes_manifest')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :kubernetes_manifest,
    method: :kubernetes_manifest,
    required_attrs: { manifest: 'test-value' },
    expected_outputs: [:id, :object],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
